import XCTest

@testable import AdventOfCode

final class Day11Tests: XCTestCase {
  func testPart1() {
    let data = """
      ...#......
      .......#..
      #.........
      ..........
      ......#...
      .#........
      .........#
      ..........
      .......#..
      #...#.....
      """
    let challenge = Day11(data: data)
    XCTAssertEqual(String(describing: challenge.part1()), "374")
  }
}
